jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [8, 11, 17, 21]
      fail-fast: true
    steps:
      - uses: actions/checkout@v4
      - name: Install Java ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'zulu'
      - name: patch
        run: |
          git config --global user.email "no-reply@github.com"
          git config --global user.name "Github Actions"
          ./waterfall p
      - name: build
        run: mvn clean install javadoc:javadoc -B
      - name: Upload JAR
        uses: actions/upload-artifact@v3
        with:
          name: waterfall-build-${{ matrix.java }}
          path: target/*.jar
